services:
  area-etl-postgres:
    container_name: "area-etl-postgres"
    image: "postgres:17"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=area_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P4ssword!
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d area_db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s