services:
  area-etl-postgres:
    container_name: area-etl-postgres
    image: postgres:17.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=area_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P4ssword!
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  area-etl-minio:
    container_name: area-etl-minio
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DOMAIN=localhost
    command:
      - server
      - --console-address=:9001
      - /data
    volumes:
      - ./minio_data:/data
